name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Upgrade
        run: |
          python -m pip install --upgrade pip xpip-build xpip-upload
          python -m pip --version
          python -m pip list
      - name: Build and Test
        run: |
          make build install test
      - name: Upload to PyPI
        run: |
          xpip-upload --token ${{ secrets.PYPI_TOKEN }} dist/*

  pypi-index:
    needs: pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install from PyPI
        run: |
          python -m pip install -r requirements.txt
          PKGNAME=$(python setup.py --name)
          VERSION=$(python setup.py --version)
          while true; do python -m pip install $PKGNAME==$VERSION && break || sleep 5; done

  docker:
    needs: pypi-index
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e "s/^refs\/tags\///")
          VERSION=${TAG_NAME#v}
          echo "Tag Name: $TAG_NAME"
          echo "Version: $VERSION"
          echo "PKG_VERSION=$VERSION" >> $GITHUB_ENV
          sleep 60
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mingzhebaosheng/xiaoya-downloader
            ghcr.io/podboy/xiaoya-downloader
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_PACKAGES }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
          build-args: |
            VERSION=${{ env.PKG_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
